### ISSUE TITLE
ctrl-q not working

### ISSUE THREAD

**Issue by poulpoulsen** [lisps/tagadd#1]
hello,
anytime i press ctrl-q, dokuwiki wants to leave the page and shutdown.
i use dokuwiki hrun on opensuse 13.1 with firefox browser.
any clues?

Regards
Poul

**Comment by lisps** [comment]
you can change the key codes in the config section 
see https://www.dokuwiki.org/plugin:tagadd#discussion
and http://css-tricks.com/snippets/javascript/javascript-keycodes/

**Comment by poulpoulsen** [comment]
hello,

thanks for the answer, but unfortunately i'm not a developer. How could i change the keycode? I don' t understand the info on both links :-(

Regards
Poul

**Comment by peterfromearth** [comment]
the plugin has know a pagetool btn. Hope this will help.

**Comment by poulpoulsen** [comment]
hello, thanks for the answer. But i do not use dokuwiki anymore.
Will close ticket.
